
styleguide: plataformatec/linters

subapps:
  - name: "Web interface"
    path: apps/dt_web

  - name: "Alarm core"
    path: apps/dt_core

  - name: "CAN bus interface"
    path: apps/dt_bus

engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  shellcheck:
    enabled: true
  remark-lint:
    enabled: true

exclude_paths:
- config
- apps/**/config/*
- apps/**/test/*
- apps/dt_web/webapp/src/assets/*
