env:
        - REBAR_DEPS_DIR=$TRAVIS_BUILD_DIR/deps

sudo: false

language: elixir

elixir:
        - 1.3.2
        - 1.3.4

otp_release:
        - 19.1

addons:
  postgresql: "9.4"

before_install:
        - . $HOME/.nvm/nvm.sh
        - nvm install 4
        - npm --version
          #- export CHROME_BIN=chromium-browser
          #- export DISPLAY=:99.0
          #before_script:
          #- sh -e /etc/init.d/xvfb start
          #- sleep 1  # give server time to start

after_script:
          - cat /home/travis/build/xadhoom/detectino-core/webapp/npm-debug.log

cache:
        directories:
                - webapp/node_modules
                - deps
                - _build

script:
        - "pushd webapp; npm install; npm run build; npm run test; popd"
        - "MIX_ENV=test mix do deps.get, deps.compile, coveralls.travis"
