env:
  - REBAR_DEPS_DIR=$TRAVIS_BUILD_DIR/deps

sudo: false

language: elixir

elixir:
  - 1.3.4

otp_release:
  - 19.1

addons:
  postgresql: "9.4"

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 6
  - npm --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
  - mkdir ~/.config && echo "--no-sandbox" > ~/.config/chromium-flags.conf;
  - npm config set spin false
  - npm config set progress false

before_script:
  - npm install -g angular-cli

cache:
  directories:
    - webapp/node_modules
    - deps
    - _build

script:
  - "pushd webapp; npm install; ng lint && ng build && ng test --single-run --progress false && popd"
  - "MIX_ENV=test mix do deps.get, deps.compile, coveralls.travis"
